version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  airflow-init:
    image: apache/airflow:2.7.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 'Ztpy-IWlUXovIU8ZoNEiuQFzT15ylojNzdshLRdTHbc='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./ebay_api_client.py:/opt/airflow/ebay_api_client.py
      - ./config.json:/opt/airflow/config.json
      - ./ebay_token.json:/opt/airflow/ebay_token.json
      - ./data_manager.py:/opt/airflow/data_manager.py
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "
    depends_on:
      - postgres

  airflow-webserver:
    image: apache/airflow:2.7.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 'Ztpy-IWlUXovIU8ZoNEiuQFzT15ylojNzdshLRdTHbc='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./ebay_api_client.py:/opt/airflow/ebay_api_client.py
      - ./config.json:/opt/airflow/config.json
      - ./ebay_token.json:/opt/airflow/ebay_token.json
      - ./data_manager.py:/opt/airflow/data_manager.py
    command: "airflow webserver --port 8080 --workers 1"
    depends_on:
      - airflow-init

  airflow-scheduler:
    image: apache/airflow:2.7.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 'Ztpy-IWlUXovIU8ZoNEiuQFzT15ylojNzdshLRdTHbc='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./ebay_api_client.py:/opt/airflow/ebay_api_client.py
      - ./config.json:/opt/airflow/config.json
      - ./ebay_token.json:/opt/airflow/ebay_token.json
      - ./data_manager.py:/opt/airflow/data_manager.py
    command: "airflow scheduler"
    depends_on:
      - airflow-init
