name: 'ebay_weather_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'clickhouse_profile'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  ebay_weather_analytics:
    silver:
      +materialized: table
      +partition_by: 'toYYYYMM(collection_timestamp)'
    gold:
      +materialized: table
      fact_listings:
        +partition_by: 'toYYYYMM(collection_timestamp)'
        +order_by: '(collection_timestamp, item_id)'
      dim_weather:
        +partition_by: 'toYYYYMM(date)'
        +order_by: '(date, weather_bucket)'
      analytics_weather_impact:
        +partition_by: 'toYYYYMM(date)'
        +order_by: '(date, weather_bucket)'

# Configuring tests
tests:
  ebay_weather_analytics:
    +store_failures: true
    +severity: error